### ISSUE TITLE
mpd controls absent

### ISSUE THREAD

**Issue by jlapeyre** [cockroach/fookebox#3]
I don't see volume controls, or queue entire album, or any mpd controls. These are the relevant lines in config.ini

```                                                                                                                                               
show_search_tab = true
enable_controls = true
enable_song_removal = true
enable_queue_album = true
```
But none of these features seem to be present. I tried uncommenting both lines that mention debugging. I get no error messages in `/var/log/apache2`.  I am using debian packages apache `2.4.17-3` and fookebox `0.7.2-1`.  Are these features available ? Would installing from source help? I've tried everything I can think of for the past six hours. Out of ideas.  If it is some kind of bug, I can file a debian bug report.

**Comment by cockroach** [comment]
The features should be available, yes, but only in the "classic" theme for now. This information seems to be missing from the documentation, sorry about that.

**Comment by cockroach** [comment]
Also, I'll be adding these controls to the non-classic theme any day now.

**Comment by cockroach** [comment]
The latest development version should fix this.

**Comment by jlapeyre** [comment]
Thank you. I don't know how to change themes. I have been upgrading possibly relevant things. I am now getting some error messages from the the web server like this:
```
Module fookebox.controllers.jukebox:2 in index, etc.
```
This is progress. I will try to sort understand the messages... and maybe switch to the development version.

**Comment by jlapeyre** [comment]
I didn't see this documented. ("theme: which theme to use", but I didn't know the names of the themes) 

But, yes
```
theme = classic
```
Gives me the classic theme back. Problem solved.

**Comment by cockroach** [comment]
Nice. With the next release you will be able to use the modern theme and still have controls, it may be a few days until I find time to create Debian packages though.
